export const metaAdsFields = {
  account: [
    'id',
    'name',
    'account_id',
    'currency',
    'timezone_name',
    'account_status',
  ],
  campaign: [
    'id',
    'name',
    'objective',
    'status',
    'effective_status',
    'buying_type',
    'created_time',
    'updated_time',
  ],
  adSet: [
    'id',
    'campaign_id',
    'name',
    'status',
    'effective_status',
    'daily_budget',
    'lifetime_budget',
    'optimization_goal',
    'billing_event',
    'start_time',
    'end_time',
  ],
  ad: [
    'id',
    'adset_id',
    'campaign_id',
    'name',
    'status',
    'effective_status',
    'creative{id}',
  ],
  insights: [
    'account_id',
    'campaign_id',
    'adset_id',
    'ad_id',
    'date_start',
    'date_stop',
    'impressions',
    'reach',
    'clicks',
    'inline_link_clicks',
    'spend',
    'cpm',
    'cpc',
    'ctr',
    'actions',
    'action_values',
  ],
} as const;

export const buildMetaFieldsParam = (
  fields: readonly string[],
): string => fields.join(',');
