<?php

defined( 'ABSPATH' ) || exit;

class Vylino_WA_Admin {
    private $repository;
    public function __construct(Vylino_WA_Repository $repository){$this->repository=$repository;}
    public function register(){add_action('admin_menu',array($this,'menu'));add_action('admin_init',array($this,'register_settings'));add_action('admin_post_vylino_wa_takeover',array($this,'takeover'));add_action('admin_post_vylino_wa_release',array($this,'release'));add_action('admin_enqueue_scripts',array($this,'assets'));}
    public function menu(){add_menu_page(__('Vylino WhatsApp','vylino-whatsapp-ai'),__('Vylino WhatsApp','vylino-whatsapp-ai'),'edit_posts','vylino-wa',array($this,'dashboard_page'),'dashicons-whatsapp',58);add_submenu_page('vylino-wa',__('Inbox','vylino-whatsapp-ai'),__('Inbox','vylino-whatsapp-ai'),'edit_posts','vylino-wa-inbox',array($this,'inbox_page'));add_submenu_page('vylino-wa',__('Settings','vylino-whatsapp-ai'),__('Settings','vylino-whatsapp-ai'),'manage_options','vylino-wa-settings',array($this,'settings_page'));}
    public function register_settings(){register_setting('vylino_wa_settings_group','vylino_wa_settings',array($this,'sanitize_settings'));}
    public function sanitize_settings($input){$old=get_option('vylino_wa_settings',array());return array('graph_version'=>sanitize_text_field($input['graph_version']??($old['graph_version']??'v23.0')),'phone_number_id'=>sanitize_text_field($input['phone_number_id']??''),'business_account_id'=>sanitize_text_field($input['business_account_id']??''),'access_token'=>sanitize_textarea_field($input['access_token']??''),'app_secret'=>sanitize_text_field($input['app_secret']??''),'verify_token'=>sanitize_text_field($input['verify_token']??($old['verify_token']??'')),'ai_provider'=>sanitize_key($input['ai_provider']??'none'),'ai_enabled'=>!empty($input['ai_enabled'])?1:0,'default_language'=>sanitize_key($input['default_language']??'auto'),'human_handoff_keywords'=>sanitize_textarea_field($input['human_handoff_keywords']??''),'retention_days'=>max(1,absint($input['retention_days']??365)));}
    public function dashboard_page(){$s=get_option('vylino_wa_settings',array());?><div class="wrap vylino-wa-wrap"><h1>Vylino WhatsApp AI CRM</h1><div class="vylino-wa-grid"><div class="vylino-wa-card"><h2>WhatsApp</h2><p><?php echo !empty($s['phone_number_id'])?'Configured':'Needs setup';?></p></div><div class="vylino-wa-card"><h2>AI Replies</h2><p><?php echo !empty($s['ai_enabled'])?'Enabled':'Disabled';?></p></div><div class="vylino-wa-card"><h2>Webhook Callback</h2><code><?php echo esc_html(rest_url('vylino-wa/v1/webhook'));?></code></div></div><p><a class="button button-primary" href="<?php echo esc_url(admin_url('admin.php?page=vylino-wa-settings'));?>">Configure</a></p></div><?php }
    public function inbox_page(){$conversation_id=isset($_GET['conversation'])?absint($_GET['conversation']):0;$rows=$this->repository->recent_conversations();$messages=$conversation_id?$this->repository->get_messages($conversation_id):array();$selected=$conversation_id?$this->repository->get_conversation($conversation_id):null;?><div class="wrap vylino-wa-wrap"><h1>WhatsApp Inbox</h1><div class="vylino-wa-inbox"><aside><?php foreach($rows as $row):?><a class="vylino-wa-thread <?php echo $conversation_id===(int)$row['id']?'is-active':'';?>" href="<?php echo esc_url(admin_url('admin.php?page=vylino-wa-inbox&conversation='.absint($row['id'])));?>"><strong><?php echo esc_html($row['profile_name']?:$row['phone']);?></strong><span><?php echo esc_html(strtoupper($row['state']).' · '.$row['status']);?></span></a><?php endforeach;?></aside><main><?php if(!$selected):?><p>Select a conversation.</p><?php else:?><div class="vylino-wa-toolbar"><strong><?php echo esc_html('Conversation #'.$conversation_id);?></strong><?php if('human'===$selected['state']):?><a class="button" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=vylino_wa_release&conversation='.$conversation_id),'vylino_wa_release_'.$conversation_id));?>">Return to AI</a><?php else:?><a class="button button-primary" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=vylino_wa_takeover&conversation='.$conversation_id),'vylino_wa_takeover_'.$conversation_id));?>">Take Over</a><?php endif;?></div><div class="vylino-wa-messages"><?php foreach($messages as $message):?><div class="vylino-wa-message is-<?php echo esc_attr($message['direction']);?>"><small><?php echo esc_html(ucfirst($message['sender_type']));?></small><p><?php echo nl2br(esc_html($message['body']));?></p></div><?php endforeach;?></div><?php endif;?></main></div></div><?php }
    public function settings_page(){$s=get_option('vylino_wa_settings',array());?><div class="wrap vylino-wa-wrap"><h1>Vylino WhatsApp Settings</h1><form method="post" action="options.php"><?php settings_fields('vylino_wa_settings_group');?><table class="form-table"><tr><th>Graph API version</th><td><input class="regular-text" name="vylino_wa_settings[graph_version]" value="<?php echo esc_attr($s['graph_version']??'v23.0');?>"></td></tr><tr><th>Phone Number ID</th><td><input class="regular-text" name="vylino_wa_settings[phone_number_id]" value="<?php echo esc_attr($s['phone_number_id']??'');?>"></td></tr><tr><th>Business Account ID</th><td><input class="regular-text" name="vylino_wa_settings[business_account_id]" value="<?php echo esc_attr($s['business_account_id']??'');?>"></td></tr><tr><th>Access Token</th><td><textarea class="large-text" rows="3" name="vylino_wa_settings[access_token]"><?php echo esc_textarea($s['access_token']??'');?></textarea></td></tr><tr><th>App Secret</th><td><input type="password" class="regular-text" name="vylino_wa_settings[app_secret]" value="<?php echo esc_attr($s['app_secret']??'');?>"></td></tr><tr><th>Verify Token</th><td><input class="regular-text" name="vylino_wa_settings[verify_token]" value="<?php echo esc_attr($s['verify_token']??'');?>"></td></tr><tr><th>AI replies</th><td><label><input type="checkbox" name="vylino_wa_settings[ai_enabled]" value="1" <?php checked(!empty($s['ai_enabled']));?>> Enable AI routing</label></td></tr><tr><th>Human handoff keywords</th><td><textarea class="large-text" rows="4" name="vylino_wa_settings[human_handoff_keywords]"><?php echo esc_textarea($s['human_handoff_keywords']??'');?></textarea></td></tr></table><?php submit_button();?></form></div><?php }
    public function takeover(){$id=absint($_GET['conversation']??0);check_admin_referer('vylino_wa_takeover_'.$id);if(!current_user_can('edit_posts')){wp_die('Permission denied.');}$this->repository->set_human_handoff($id,'Manual takeover',get_current_user_id());wp_safe_redirect(admin_url('admin.php?page=vylino-wa-inbox&conversation='.$id));exit;}
    public function release(){$id=absint($_GET['conversation']??0);check_admin_referer('vylino_wa_release_'.$id);if(!current_user_can('edit_posts')){wp_die('Permission denied.');}$this->repository->release_to_ai($id,get_current_user_id());wp_safe_redirect(admin_url('admin.php?page=vylino-wa-inbox&conversation='.$id));exit;}
    public function assets($hook){if(false===strpos($hook,'vylino-wa')){return;}wp_enqueue_style('vylino-wa-admin',VYLINO_WA_URL.'assets/css/admin.css',array(),VYLINO_WA_VERSION);}
}
