<?php

defined( 'ABSPATH' ) || exit;

class Vylino_WA_Router {
    private $repository; private $client; private $ai;
    public function __construct(Vylino_WA_Repository $repository,Vylino_WA_WhatsApp_Client $client,Vylino_WA_AI_Manager $ai){$this->repository=$repository;$this->client=$client;$this->ai=$ai;}
    public function handle_webhook_payload(array $payload){$processed=0;foreach(($payload['entry']??array()) as $entry){foreach(($entry['changes']??array()) as $change){$value=$change['value']??array();$contacts=$value['contacts']??array();foreach(($value['messages']??array()) as $message){$from=sanitize_text_field($message['from']??'');if(''===$from){continue;}$body=$this->extract_message_body($message);$profile_name=!empty($contacts[0]['profile']['name'])?sanitize_text_field($contacts[0]['profile']['name']):'';$contact_id=$this->repository->upsert_contact($from,$profile_name,$from);$conversation_id=$this->repository->get_or_create_open_conversation($contact_id);$this->repository->save_message(array('conversation_id'=>$conversation_id,'contact_id'=>$contact_id,'wa_message_id'=>sanitize_text_field($message['id']??''),'direction'=>'in','sender_type'=>'customer','message_type'=>sanitize_key($message['type']??'unknown'),'body'=>$body,'payload'=>$message,'status'=>'received'));$processed++;$this->maybe_handoff_or_reply($conversation_id,$contact_id,$from,$body);}}}return $processed;}
    private function maybe_handoff_or_reply($conversation_id,$contact_id,$from,$body){$conversation=$this->repository->get_conversation($conversation_id);if(!$conversation||'human'===$conversation['state']||empty($conversation['ai_enabled'])){return;}$reason=$this->detect_handoff($body);if($reason){$this->repository->set_human_handoff($conversation_id,$reason);do_action('vylino_wa_handoff_requested',$conversation_id,$contact_id,$reason);return;}$reply=$this->ai->generate($conversation_id,$body);if(is_wp_error($reply)||!is_string($reply)||''===trim($reply)){return;}$send=$this->client->send_text($from,$reply);if(is_wp_error($send)){$this->repository->log_event($conversation_id,'send_failed',array('error'=>$send->get_error_message()),0,$contact_id);return;}$this->repository->save_message(array('conversation_id'=>$conversation_id,'contact_id'=>$contact_id,'wa_message_id'=>$send['messages'][0]['id']??'','direction'=>'out','sender_type'=>'ai','message_type'=>'text','body'=>$reply,'payload'=>$send,'status'=>'sent'));}
    private function detect_handoff($body){$settings=get_option('vylino_wa_settings',array());$keywords=array_filter(array_map('trim',explode(',',strtolower((string)($settings['human_handoff_keywords']??'')))));$haystack=strtolower(wp_strip_all_tags((string)$body));foreach($keywords as $keyword){if(''!==$keyword&&false!==strpos($haystack,$keyword)){return sprintf('Keyword detected: %s',$keyword);}}return false;}
    private function extract_message_body(array $message){$type=$message['type']??'unknown';if('text'===$type){return sanitize_textarea_field($message['text']['body']??'');}if('button'===$type){return sanitize_text_field($message['button']['text']??'');}if('interactive'===$type){return sanitize_text_field($message['interactive']['button_reply']['title']??$message['interactive']['list_reply']['title']??'[Interactive message]');}return sprintf('[%s message]',sanitize_key($type));}
}
