<?php

defined( 'ABSPATH' ) || exit;

class Vylino_WA_REST {
    private $router; private $repository; private $client;
    public function __construct(Vylino_WA_Router $router,Vylino_WA_Repository $repository,Vylino_WA_WhatsApp_Client $client){$this->router=$router;$this->repository=$repository;$this->client=$client;}
    public function register_routes(){
        register_rest_route('vylino-wa/v1','/webhook',array(array('methods'=>WP_REST_Server::READABLE,'callback'=>array($this,'verify_webhook'),'permission_callback'=>'__return_true'),array('methods'=>WP_REST_Server::CREATABLE,'callback'=>array($this,'receive_webhook'),'permission_callback'=>'__return_true')));
        register_rest_route('vylino-wa/v1','/conversations/(?P<id>\d+)/send',array('methods'=>WP_REST_Server::CREATABLE,'callback'=>array($this,'agent_send'),'permission_callback'=>function(){return current_user_can('edit_posts');},'args'=>array('message'=>array('required'=>true,'sanitize_callback'=>'sanitize_textarea_field'))));
    }
    public function verify_webhook(WP_REST_Request $request){$s=get_option('vylino_wa_settings',array());$mode=$request->get_param('hub_mode')?:$request->get_param('hub.mode');$token=$request->get_param('hub_verify_token')?:$request->get_param('hub.verify_token');$challenge=$request->get_param('hub_challenge')?:$request->get_param('hub.challenge');if('subscribe'===$mode&&!empty($s['verify_token'])&&hash_equals((string)$s['verify_token'],(string)$token)){return new WP_REST_Response((string)$challenge,200,array('Content-Type'=>'text/plain'));}return new WP_Error('vylino_wa_webhook_verify_failed',__('Webhook verification failed.','vylino-whatsapp-ai'),array('status'=>403));}
    public function receive_webhook(WP_REST_Request $request){$s=get_option('vylino_wa_settings',array());$raw=$request->get_body();if(!Vylino_WA_Security::verify_meta_signature($raw,$request->get_header('x-hub-signature-256'),$s['app_secret']??'')){return new WP_Error('vylino_wa_bad_signature',__('Invalid webhook signature.','vylino-whatsapp-ai'),array('status'=>403));}$payload=json_decode($raw,true);if(!is_array($payload)){return new WP_Error('vylino_wa_bad_payload',__('Invalid webhook payload.','vylino-whatsapp-ai'),array('status'=>400));}return rest_ensure_response(array('ok'=>true,'processed'=>$this->router->handle_webhook_payload($payload)));}
    public function agent_send(WP_REST_Request $request){$conversation_id=absint($request['id']);$message=(string)$request->get_param('message');$conversation=$this->repository->get_conversation($conversation_id);if(!$conversation){return new WP_Error('vylino_wa_not_found',__('Conversation not found.','vylino-whatsapp-ai'),array('status'=>404));}global $wpdb;$contact=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}vylino_wa_contacts WHERE id = %d",$conversation['contact_id']),ARRAY_A);if(!$contact){return new WP_Error('vylino_wa_contact_not_found',__('Contact not found.','vylino-whatsapp-ai'),array('status'=>404));}$this->repository->set_human_handoff($conversation_id,'Agent replied',get_current_user_id());$send=$this->client->send_text($contact['phone']?:$contact['wa_id'],$message);if(is_wp_error($send)){return $send;}$this->repository->save_message(array('conversation_id'=>$conversation_id,'contact_id'=>$conversation['contact_id'],'wa_message_id'=>$send['messages'][0]['id']??'','direction'=>'out','sender_type'=>'agent','message_type'=>'text','body'=>$message,'payload'=>$send,'status'=>'sent'));return rest_ensure_response(array('ok'=>true));}
}
